<div style="background-color:#7BAFD4;border-radius:18px;padding:22px 26px;margin-bottom:18px;">
<div style="font-family:Impact,'Arial Black',Arial,sans-serif;font-size:42px;font-weight:900;letter-spacing:2px;line-height:1;color:white;">GEOG 592</div>
<div style="font-family:Arial,Helvetica,sans-serif;font-size:22px;font-weight:700;color:#13294B;margin-top:8px;">GIS Programming</div>
<div style="font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#13294B;margin-top:6px;">GeoPandas — GeoDataFrames and Geometry</div></div>

# From pandas DataFrames to spatial DataFrames

GeoPandas extends pandas by adding geometry and coordinate reference system information.

By the end of this module, you should be able to read spatial data, identify a GeoDataFrame, inspect geometry and CRS, recognize geometry types, use familiar pandas operations, and make a quick map.

## Why GeoPandas matters

A GIS dataset is more than a table. Each row can also contain a geometry.

In [4]:
# Run this only if geopandas is not installed.
# %pip install geopandas

In [5]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

## Read a spatial file

In [6]:
stops = gpd.read_file("chapel_hill_bus_stops.geojson")
# originally from https://gis-portal.townofchapelhill.org/server/rest/services/OpenData/Bus_Stops/FeatureServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson
# https://gis-portal.townofchapelhill.org/server/rest/services/
# Useful API Code: 0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson

stops

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,NAME,TYPE,CATEGORY_1,Acres,GlobalID,Acquired,Year,Shape__Area,Shape__Length,geometry
0,1,4.390758e+05,3466.65190,625,624,09/21/2005,A10.1,ORANGE COUNTY,9950114431,2.5..9G,...,Lewis' Heartleaf Preserve,Parkland & open space,Open space,10.079793,{F8631965-0D35-433C-8905-CDB60CEBD9DF},1.127261e+12,2005,6.281121e+04,1309.388751,"POLYGON ((-79.16178 36.22637, -79.16177 36.226..."
1,2,5.229943e+05,3437.57045,2735,2734,02/27/2004,A12.22,ORANGE COUNTY,9868045156,2.34..3,...,Cedar Grove Park (additional land),Parkland & open space,Open space,12.006297,{7BC4B680-934E-4F45-A5A6-848DA677E36B},1.077840e+12,2004,7.472755e+04,1298.205646,"POLYGON ((-79.13185 36.18019, -79.13185 36.180..."
2,3,2.901162e+05,4303.44333,2856,2855,11/07/2000,A7.61,ORANGE COUNTY,0818132024,1.21..32,...,Little River Regional Park,Parkland & open space,Existing park,6.660151,{208C409A-D322-4A31-817D-809233335151},9.735552e+11,2000,4.145020e+04,1629.727739,"POLYGON ((-78.96214 36.1786, -78.9615 36.17818..."
3,4,5.430328e+06,11547.06681,3535,3534,11/07/2000,A128.14,ORANGE COUNTY,0807984796,1.21..32A,...,Little River Regional Park,Parkland & open space,Existing park,124.663187,{9C0693DF-31AE-4701-B3ED-568C6CF2D41B},9.735552e+11,2000,7.756036e+05,4362.803990,"POLYGON ((-78.96311 36.16803, -78.96458 36.159..."
4,5,7.067510e+06,35133.58931,3597,3596,08/04/1967,A156.57,ORANGE COUNTY,9857642370,2.45..5,...,Lake Orange,Parkland & open space,Water & othr utiliti,162.247694,{DF5E7EA1-D1EE-4035-9D8F-D65968CFA79D},-7.603200e+10,1967,1.009220e+06,13281.510025,"POLYGON ((-79.14132 36.16565, -79.14105 36.165..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,64,6.449701e+05,5641.07811,22490,22489,05/18/1989,S638077,ORANGE COUNTY,9891991328,7.6..92,...,Piney Mountain subdivision (Ph1 & 2),Parkland & open space,Rec & open space,14.806476,{F3162DA0-5847-465E-BB4B-A361E9A827DF},6.113664e+11,1989,8.386166e+04,2123.808981,"POLYGON ((-79.00298 36.00408, -79.00175 36.004..."
64,65,2.772936e+06,10256.43099,0,0,,,SCHOOL BOARD,,,...,,OPEN SPACE,,0.000000,{D7B8F32F-FDEC-45F1-8029-CEDDCBE399AE},NaN,,3.940999e+05,3866.409721,"POLYGON ((-79.10561 35.96395, -79.105 35.96395..."
65,66,1.132557e+05,1735.65932,0,0,05/28/2014,2.58,ORANGE COUNTY,9891919120,,...,New Hope Preserve,Parkland & open space,Future park,3.000000,{7583D09E-D5AC-487F-BFC4-771A0BED2A34},1.401235e+12,2014,1.610253e+04,654.140212,"POLYGON ((-78.99928 35.97958, -78.99935 35.979..."
66,67,4.939797e+05,8802.23809,0,0,10/22/2019,11.34,ORANGE COUNTY,9820428146,,...,Mountains to Sea Trail access,Parkland & open space,Recreation,11.340000,{BE2D21C4-EE51-4931-A8BF-95B3D1E47A1B},1.571702e+12,2019,7.018862e+04,3317.850579,"POLYGON ((-79.25034 35.95436, -79.2509 35.9536..."
67,68,2.465293e+06,7688.26093,0,0,03/19/2020,59.86,ANDERSON NELS & NANCY,9885995812,,...,Holden Roberts,Agriculture,Agriculture easement,56.753000,{21CC6CFD-D6AB-4070-B749-61E5B8234574},1.584576e+12,2020,3.516669e+05,2904.821373,"POLYGON ((-79.03342 36.10811, -79.03342 36.108..."

In [7]:
type(stops)

geopandas.geodataframe.GeoDataFrame

## Familiar pandas operations still work

In [8]:
stops.head()

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,NAME,TYPE,CATEGORY_1,Acres,GlobalID,Acquired,Year,Shape__Area,Shape__Length,geometry
0,1,4.390758e+05,3466.65190,625,624,09/21/2005,A10.1,ORANGE COUNTY,9950114431,2.5..9G,...,Lewis' Heartleaf Preserve,Parkland & open space,Open space,10.079793,{F8631965-0D35-433C-8905-CDB60CEBD9DF},1.127261e+12,2005,6.281121e+04,1309.388751,"POLYGON ((-79.16178 36.22637, -79.16177 36.226..."
1,2,5.229943e+05,3437.57045,2735,2734,02/27/2004,A12.22,ORANGE COUNTY,9868045156,2.34..3,...,Cedar Grove Park (additional land),Parkland & open space,Open space,12.006297,{7BC4B680-934E-4F45-A5A6-848DA677E36B},1.077840e+12,2004,7.472755e+04,1298.205646,"POLYGON ((-79.13185 36.18019, -79.13185 36.180..."
2,3,2.901162e+05,4303.44333,2856,2855,11/07/2000,A7.61,ORANGE COUNTY,0818132024,1.21..32,...,Little River Regional Park,Parkland & open space,Existing park,6.660151,{208C409A-D322-4A31-817D-809233335151},9.735552e+11,2000,4.145020e+04,1629.727739,"POLYGON ((-78.96214 36.1786, -78.9615 36.17818..."
3,4,5.430328e+06,11547.06681,3535,3534,11/07/2000,A128.14,ORANGE COUNTY,0807984796,1.21..32A,...,Little River Regional Park,Parkland & open space,Existing park,124.663187,{9C0693DF-31AE-4701-B3ED-568C6CF2D41B},9.735552e+11,2000,7.756036e+05,4362.803990,"POLYGON ((-78.96311 36.16803, -78.96458 36.159..."
4,5,7.067510e+06,35133.58931,3597,3596,08/04/1967,A156.57,ORANGE COUNTY,9857642370,2.45..5,...,Lake Orange,Parkland & open space,Water & othr utiliti,162.247694,{DF5E7EA1-D1EE-4035-9D8F-D65968CFA79D},-7.603200e+10,1967,1.009220e+06,13281.510025,"POLYGON ((-79.14132 36.16565, -79.14105 36.165..."

In [9]:
stops.shape

(68, 23)

In [10]:
stops.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [11]:
stops.columns

Index(['FID', 'AREA_', 'PERIMETER', 'PARCELS_', 'PARCELS_ID', 'CREATION',
       'SIZE', 'OWNER', 'PIN', 'TMBL', 'DESC_', 'DEEDREF', 'PLAT_BKPG', 'NAME',
       'TYPE', 'CATEGORY_1', 'Acres', 'GlobalID', 'Acquired', 'Year',
       'Shape__Area', 'Shape__Length', 'geometry'],
      dtype='str')

In [12]:
print(stops[["NAME","geometry"]])
print(type(stops[["NAME","geometry"]]))

                                    NAME  \
0              Lewis' Heartleaf Preserve
1     Cedar Grove Park (additional land)
2             Little River Regional Park
3             Little River Regional Park
4                            Lake Orange
..                                   ...
63  Piney Mountain subdivision (Ph1 & 2)
64
65                     New Hope Preserve
66         Mountains to Sea Trail access
67                        Holden Roberts

                                             geometry
0   POLYGON ((-79.16178 36.22637, -79.16177 36.226...
1   POLYGON ((-79.13185 36.18019, -79.13185 36.180...
2   POLYGON ((-78.96214 36.1786, -78.9615 36.17818...
3   POLYGON ((-78.96311 36.16803, -78.96458 36.159...
4   POLYGON ((-79.14132 36.16565, -79.14105 36.165...
..                                                ...
63  POLYGON ((-79.00298 36.00408, -79.00175 36.004...
64  POLYGON ((-79.10561 35.96395, -79.105 35.96395...
65  POLYGON ((-78.99928 35.97958, -78.99935 35.979...
66  POLYGON ((-79.25034 35.95436, -79.2509 35.9536...
67  POLYGON ((-79.03342 36.10811, -79.03342 36.108...

[68 rows x 2 columns]
<class 'geopandas.geodataframe.GeoDataFrame'>

## The geometry column

In [13]:
print(stops.geometry.head())
print(type(stops.geometry))

0    POLYGON ((-79.16178 36.22637, -79.16177 36.226...
1    POLYGON ((-79.13185 36.18019, -79.13185 36.180...
2    POLYGON ((-78.96214 36.1786, -78.9615 36.17818...
3    POLYGON ((-78.96311 36.16803, -78.96458 36.159...
4    POLYGON ((-79.14132 36.16565, -79.14105 36.165...
Name: geometry, dtype: geometry
<class 'geopandas.geoseries.GeoSeries'>

In [14]:
first_geometry = stops.geometry.iloc[0]
print(first_geometry)
print(type(first_geometry))

POLYGON ((-79.1617825023534 36.2263707120848, -79.1617725091417 36.226265881352, -79.1617630113513 36.2261662461956, -79.1669411862775 36.2262458192559, -79.1655459407132 36.2276598779749, -79.1617825023534 36.2263707120848))
<class 'shapely.geometry.polygon.Polygon'>

Remember what you know about objects and dot notation:

- `stops` is a GeoDataFrame object
- `stops.geometry` is an attribute
- `stops.head()` is a method
- each individual geometry is also an object

## Geometry types

In [15]:
stops.geom_type

0     Polygon
1     Polygon
2     Polygon
3     Polygon
4     Polygon
       ...
63    Polygon
64    Polygon
65    Polygon
66    Polygon
67    Polygon
Length: 68, dtype: str

In [16]:
urban_area = gpd.read_file("urban_area.geojson")
## from https://gis-portal.townofchapelhill.org/server/rest/services/OpenData/UrbanServiceBoundary/FeatureServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson
print(urban_area.geom_type)
print(urban_area.crs)
urban_area

DataSourceError: urban_area.geojson: No such file or directory

## Quick plotting

In [ ]:
fig, ax = plt.subplots(figsize=(7,7))
urban_area.plot(ax=ax, edgecolor="black")
stops.plot(ax=ax, markersize=1, c="red")
ax.set_title("Bus Stops & Urban Service Boundary")
plt.show()

The order that you call the layer will have an effect on how it is displayed. 
Notice the difference below when we call the points before the polygon.

In [ ]:
fig, ax = plt.subplots(figsize=(7,7))
stops.plot(ax=ax, markersize=1, c="red")
urban_area.plot(ax=ax, edgecolor="black")
ax.set_title("Bus Stops & Urban Service Boundary")
plt.show()

## Attribute filtering still works

In [ ]:
list(stops.columns) ## to see all the columns

In [ ]:

stops["CL"].value_counts() # look at the column containing info about the "CL" route

In [ ]:
#1 means that it has a stop and #0 means it does not
CL_stops = stops[stops["CL"] == 1].copy() ## selecting places where CL stops 
CL_stops

In [ ]:
fig, ax = plt.subplots(figsize=(7,7))
urban_area.plot(ax=ax, edgecolor="black")
CL_stops.plot(ax=ax, markersize=1, c="red")
ax.set_title("CL Stops")
plt.show()

## Practice

Using another Chapel Hill geoJSON:

- download two geoJSONs from the Chapel Hill Server (not Stops, not the Boundary)
- inspect the type, shape, and columns
- select the name and geometry columns
- inspect the first geometry
- determine geometry types
- inspect the CRS
- filter the data
- make a copy of the result
- plot the selected features
- publish your work by uploading your JN to your GitHub (week06)

## What to remember

```python
gpd.read_file(...)
gdf.head()
gdf.shape
gdf.geometry
gdf.geom_type
gdf.crs
gdf.plot()
```

The main idea is that GeoPandas keeps the table structure of pandas and adds geometry.